export function generateFetchClientCode(): string {
  return [
    "import { HullaAPIError } from '@hulla/api/client'",
    "import type { ClientHeaders, ClientRequestOptions } from '@hulla/api/client'",
    "export { HullaAPIError } from '@hulla/api/client'",
    '',
    'export type OpenAPIRequest = {',
    '  method: string',
    '  path: string',
    '  params?: unknown',
    '  query?: unknown',
    '  headers?: unknown',
    '  body?: unknown',
    '}',
    '',
    'export type FetchOpenAPIClientOptions = {',
    '  baseUrl?: string',
    '  fetch?: typeof fetch',
    '  headers?: ClientHeaders',
    '  serializeQuery?: (query: unknown) => string',
    '}',
    '',
    'export type FetchOpenAPIClient = (<T>(request: OpenAPIRequest, options?: ClientRequestOptions) => Promise<T>) & {',
    '  withBaseUrl: (baseUrl: string) => FetchOpenAPIClient',
    '}',
    '',
    'export function createFetchOpenAPIClient(options: FetchOpenAPIClientOptions = {}): FetchOpenAPIClient {',
    '  return createClient(options.baseUrl ?? "", options.fetch ?? globalThis.fetch, options.headers, options.serializeQuery ?? defaultSerializeQuery)',
    '}',
    '',
    'function createClient(',
    '  baseUrl: string,',
    '  fetcher: typeof fetch,',
    '  defaultHeaders: ClientHeaders | undefined,',
    '  serializeQuery: (query: unknown) => string',
    '): FetchOpenAPIClient {',
    '  const client = (async <T>(request: OpenAPIRequest, options: ClientRequestOptions = {}): Promise<T> => {',
    '    const url = buildUrl(baseUrl, request, serializeQuery)',
    '    const configuredHeaders = typeof defaultHeaders === "function" ? await defaultHeaders() : defaultHeaders',
    '    const headers = mergeHeaders(configuredHeaders, request.headers, options.headers)',
    '    const init: RequestInit = {',
    '      method: request.method,',
    '      headers,',
    '      signal: options.signal,',
    '    }',
    '',
    '    if (request.body !== undefined) {',
    '      if (!headers.has("content-type")) headers.set("content-type", "application/json")',
    '      init.body = JSON.stringify(request.body)',
    '    }',
    '',
    '    const response = await fetcher(url, init)',
    '    const body = await parseResponseBody(response)',
    '',
    '    if (!response.ok) {',
    '      const error = errorDetails(body)',
    '      throw new HullaAPIError(response, { ...error, body })',
    '    }',
    '',
    '    return body as T',
    '  }) as FetchOpenAPIClient',
    '',
    '  client.withBaseUrl = (nextBaseUrl) =>',
    '    createClient(joinBaseUrl(baseUrl, nextBaseUrl), fetcher, defaultHeaders, serializeQuery)',
    '',
    '  return client',
    '}',
    '',
    'function buildUrl(',
    '  baseUrl: string,',
    '  request: OpenAPIRequest,',
    '  serializeQuery: (query: unknown) => string',
    '): string {',
    '  let path = request.path',
    '  const params = toRecord(request.params)',
    '',
    '  for (const [key, value] of Object.entries(params)) {',
    '    path = path.replace(`{${key}}`, encodeURIComponent(String(value)))',
    '    path = path.replace(`:${key}`, encodeURIComponent(String(value)))',
    '  }',
    '',
    '  const search = serializeQuery(request.query)',
    '  const suffix = search.length === 0 ? "" : `?${search.replace(/^\\?/, "")}`',
    '',
    '  return `${baseUrl}${path}${suffix}`',
    '}',
    '',
    'function defaultSerializeQuery(query: unknown): string {',
    '  const search = new URLSearchParams()',
    '',
    '  for (const [key, value] of Object.entries(toRecord(query))) {',
    '    if (value === undefined) continue',
    '    const values = Array.isArray(value) ? value : [value]',
    '',
    '    for (const item of values) {',
    '      search.append(key, serializeQueryValue(item))',
    '    }',
    '  }',
    '',
    '  return search.toString()',
    '}',
    '',
    'function serializeQueryValue(value: unknown): string {',
    '  if (value === null) return ""',
    '  return typeof value === "object" ? JSON.stringify(value) : String(value)',
    '}',
    '',
    'function mergeHeaders(',
    '  defaultHeaders: HeadersInit | undefined,',
    '  requestHeaders: unknown,',
    '  callHeaders: HeadersInit | undefined,',
    '): Headers {',
    '  const headers = new Headers(defaultHeaders)',
    '',
    '  if (requestHeaders !== undefined) {',
    '    new Headers(requestHeaders as HeadersInit).forEach((value, key) => headers.set(key, value))',
    '  }',
    '  new Headers(callHeaders).forEach((value, key) => headers.set(key, value))',
    '',
    '  return headers',
    '}',
    '',
    'async function parseResponseBody(response: Response): Promise<unknown> {',
    '  if (response.status === 204 || response.status === 205) return undefined',
    '  const text = await response.text()',
    '  if (text.length === 0) return undefined',
    '',
    '  const contentType = response.headers.get("content-type")?.toLowerCase() ?? ""',
    '  if (contentType.includes("application/json") || contentType.includes("+json")) {',
    '    return JSON.parse(text) as unknown',
    '  }',
    '',
    '  return text',
    '}',
    '',
    'function errorDetails(body: unknown): { code: string; message?: string } {',
    '  const record = toRecord(body)',
    '  return {',
    '    code: typeof record.code === "string" ? record.code : "UNKNOWN_ERROR",',
    '    ...(typeof record.message === "string" ? { message: record.message } : {}),',
    '  }',
    '}',
    '',
    'function toRecord(value: unknown): Record<string, unknown> {',
    '  return value !== null && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}',
    '}',
    '',
    'function joinBaseUrl(left: string, right: string): string {',
    '  if (right.length === 0) return left',
    '  if (/^https?:\\/\\//.test(right)) return right',
    '  return `${left.replace(/\\/+$/, "")}/${right.replace(/^\\/+/, "")}`',
    '}',
    '',
  ].join('\n')
}
