name: PR Check - Lint, Test, Build

on:
  push:

jobs:
  runtime:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        # for some reason in CI env bun install does not install dependencies in sub-directories, even though it does locally, doing it manually for now even though it does slow thing down a bit
        run: |
          pnpm install --frozen-lockfile --prefer-offline

      - name: Run lint fix and check
        run: |
          pnpm run format
          pnpm run lint

      - name: Test
        run: |
          pnpm run test

      - name: Build
        # Note we use a separate build using bunchee (rollup + swc) over bun, for slightly smaller bundle size & other than .js outputs
        run: |
          pnpm run build