name: PR Check - Lint, Test, Build

on:
  push:

jobs:
  runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        # for some reason in CI env bun install does not install dependencies in sub-directories, even though it does locally, doing it manually for now even though it does slow thing down a bit
        run: |
          bun install
          cd packages/core && bun install && cd ../request && bun install && cd ../swr && bun install && cd ../query
          cd ../..

      - name: Run lint fix and check
        run: |
          bun run format
          bun run lint

      - name: Test
        run: |
          bun run test

      - name: Build
        # Note we use a separate build using bunchee (rollup + swc) over bun, for slightly smaller bundle size & other than .js outputs
        run: |
          bun run build