name: PR Check - Lint, Test, Build

on:
  push:

jobs:
  runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          bun install

  lint:
    needs: runtime
    runs-on: ubuntu-latest
    steps:
      - name: Run lint fix and check
        run: |
          bun run prettier
          bun run lint

  test:
    needs: runtime
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          bun test

  build:
    needs: runtime
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          bun run build
