name: PR Check - Lint, Test, Build

on:
  push:

jobs:
  runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          bun install
          cd integrations/query
          bun install
          cd ../swr
          bun install
          cd ../..

      - name: Run lint fix and check
        run: |
          bun run prettier
          bun run lint

      - name: Test
        run: |
          bun test

      - name: Build
        # Note we use a separate build using bunchee (rollup + swc) over bun, for slightly smaller bundle size & other than .js outputs
        run: |
          bun run build